# Generated by Django 3.1.1 on 2020-11-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=None, verbose_name='Address'),
        ),
    ]
