# Generated by Django 3.1.1 on 2020-11-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201111_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='organization',
            new_name='user',
        ),
    ]
